export enum SocialProvider {
  GOOGLE = "GOOGLE",
  LINKEDIN = "LINKEDIN",
  TWITTER = "TWITTER",
  FACEBOOK = "FACEBOOK",
  NEXTCLOUD = "NEXTCLOUD",
  TELEGRAM = "TELEGRAM",
  GITHUB = "GITHUB",
  WEBSITE = "WEBSITE",
  OTHER = "OTHER",
  WORDPRESS = "WORDPRESS",
  CANVA = "CANVA",
  INSTAGRAM = "INSTAGRAM",
  WHATSAPP = "WHATSAPP",
  OPEN_ROUTER = "OPEN_ROUTER",
  BREVO = "BREVO",
}

export enum SkillCategory {
  TECHNICAL = "TECHNICAL",
  SOFT_SKILL = "SOFT_SKILL",
  LANGUAGE = "LANGUAGE",
  OTHER = "OTHER",
}

export enum PublicationStatus {
  DRAFT = "DRAFT",
  PUBLISHED = "PUBLISHED",
  ARCHIVED = "ARCHIVED",
}

export enum DocumentType {
  INPUT = "INPUT",
  OUTPUT = "OUTPUT",
}

export enum AnnouncementSeverity {
  INFO = "INFO",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum ProjectStatus {
  PLANNING = "PLANNING",
  IN_PROGRESS = "IN_PROGRESS",
  ON_HOLD = "ON_HOLD",
  COMPLETED = "COMPLETED",
  CANCELLED = "CANCELLED",
}

export enum TaskStatus {
  TODO = "TODO",
  IN_PROGRESS = "IN_PROGRESS",
  IN_REVIEW = "IN_REVIEW",
  DONE = "DONE",
  BLOCKED = "BLOCKED",
  CANCELLED = "CANCELLED",
}

export enum TaskPriority {
  NONE = "NONE",
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  URGENT = "URGENT",
}

export enum TaskLinkType {
  RELATES_TO = "RELATES_TO",
  BLOCKS = "BLOCKS",
  IS_BLOCKED_BY = "IS_BLOCKED_BY",
}

export enum CustomFieldType {
  TEXT = "TEXT",
  NUMBER = "NUMBER",
  DATE = "DATE",
  SELECT = "SELECT",
}

export enum ActivityActionType {
  TASK_CREATED = "TASK_CREATED",
  TASK_UPDATED = "TASK_UPDATED",
  TASK_DELETED = "TASK_DELETED",
  TASK_MOVED = "TASK_MOVED",
  COMMENT_CREATED = "COMMENT_CREATED",
  COMMENT_UPDATED = "COMMENT_UPDATED",
  COMMENT_DELETED = "COMMENT_DELETED",
  PROJECT_CREATED = "PROJECT_CREATED",
  PROJECT_UPDATED = "PROJECT_UPDATED",
}

export enum JobStatus {
  PENDING = "PENDING",
  RUNNING = "RUNNING",
  COMPLETED = "COMPLETED",
  FAILED = "FAILED",
  CANCELLED = "CANCELLED",
}

export enum NotificationType {
  SYSTEM_BROADCAST = "SYSTEM_BROADCAST",
  TASK_ASSIGNMENT = "TASK_ASSIGNMENT",
  COMMENT_MENTION = "COMMENT_MENTION",
  PROJECT_INVITE = "PROJECT_INVITE",
  INTEGRATION_HEALTH_ALERT = "INTEGRATION_HEALTH_ALERT",
}

export enum NotificationSeverity {
  LOW = "LOW",
  MEDIUM = "MEDIUM",
  HIGH = "HIGH",
  CRITICAL = "CRITICAL",
}

export enum EmailDigestFrequency {
  NONE = "NONE",
  DAILY = "DAILY",
  WEEKLY = "WEEKLY",
  IMMEDIATELY = "IMMEDIATELY",
}

export enum WorkflowActionType {
  CREATE_TASK = "CREATE_TASK",
  UPDATE_TASK_STATUS = "UPDATE_TASK_STATUS",
  ADD_COMMENT = "ADD_COMMENT",
  ASSIGN_TASK = "ASSIGN_TASK",
  SEND_TELEGRAM_MESSAGE = "SEND_TELEGRAM_MESSAGE",
  SEND_EMAIL_BREVO = "SEND_EMAIL_BREVO",
  SEND_WEBHOOK = "SEND_WEBHOOK",
  SEND_GOOGLE_CHAT_MESSAGE = "SEND_GOOGLE_CHAT_MESSAGE",
}

export enum WorkflowRunStatus {
  RUNNING = "RUNNING",
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}

export enum ViewType {
  KANBAN = "KANBAN",
  LIST = "LIST",
  CALENDAR = "CALENDAR",
  GANTT = "GANTT",
  BACKLOG = "BACKLOG",
  WHITEBOARD = "WHITEBOARD",
}

export enum WidgetType {
  STATS_COUNTER = "STATS_COUNTER",
  TASK_LIST = "TASK_LIST",
  BURNDOWN_CHART = "BURNDOWN_CHART",
  TIME_TRACKING_REPORT = "TIME_TRACKING_REPORT",
  PIE_CHART = "PIE_CHART",
  GOAL_TRACKING = "GOAL_TRACKING",
  LEAD_CYCLE_TIME_CHART = "LEAD_CYCLE_TIME_CHART",
}

export enum GoalStatus {
  ON_TRACK = "ON_TRACK",
  AT_RISK = "AT_RISK",
  OFF_TRACK = "OFF_TRACK",
  ACHIEVED = "ACHIEVED",
  NOT_STARTED = "NOT_STARTED",
}

export enum KeyResultType {
  NUMBER = "NUMBER",
  PERCENTAGE = "PERCENTAGE",
  CURRENCY = "CURRENCY",
  BOOLEAN = "BOOLEAN",
}

export enum InteractionType {
  EMAIL = "EMAIL",
  CALL = "CALL",
  MEETING = "MEETING",
  SOCIAL = "SOCIAL",
}

export enum IntegrationProvider {
  GOOGLE = "GOOGLE",
  LINKEDIN = "LINKEDIN",
  TWITTER = "TWITTER",
  FACEBOOK = "FACEBOOK",
  NEXTCLOUD = "NEXTCLOUD",
  TELEGRAM = "TELEGRAM",
  GITHUB = "GITHUB",
  WEBSITE = "WEBSITE",
  WORDPRESS = "WORDPRESS",
  CANVA = "CANVA",
  INSTAGRAM = "INSTAGRAM",
  WHATSAPP = "WHATSAPP",
  OPEN_ROUTER = "OPEN_ROUTER",
  BREVO = "BREVO",
}

export enum IntegrationHealthStatus {
  OK = "OK",
  ERROR = "ERROR",
  DISABLED = "DISABLED",
}

export enum ApiCallStatus {
  SUCCESS = "SUCCESS",
  FAILED = "FAILED",
}

export enum WebhookAction {
  CREATE_TASK = "CREATE_TASK",
}

export enum IntegrationCategory {
  OAUTH = "OAUTH",
  API_KEY = "API_KEY",
  WEBHOOK = "WEBHOOK",
}